<?php
/**
 * @var FormView $formView
 */
use Simplon\Form\View\FormView;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>simplon/form</title>

    <link rel="stylesheet" href="/templates/css/style.css">
</head>
<body>
<div class="content">
    <?= $formView->setUrl('/songs/' . $id)->setMethod('post')->render(__DIR__ . '/form.phtml') ?>
</div>

<?= $formView->setComponentDir('/components')->renderAssets() ?>
</body>
</html>